[package]
name = "miniscript"
version = "0.5.5"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
repository = "https://github.com/apoelstra/miniscript"
description = "Miniscript: a subset of Bitcoin Script designed for analysis"
license = "CC0-1.0"

[features]
fuzztarget = ["secp256k1/fuzztarget"]
compiler = [ "arrayvec" ]
trace = []
unstable = []

[dependencies]
bitcoin = "0.18"
bitcoin_hashes = "0.3"

[dependencies.arrayvec]
optional = true
version = "0.4"

[dependencies.secp256k1]
version = "0.12"

[dependencies.serde]
version = "1.0"
optional = true

